# NUMPY BASIC COMMANDS

In [1]:
import numpy as np

### A simple ndarray

In [3]:
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


### Minimum dimension attribute

In [13]:
a = np.array([1,2,3,4,5], ndmin=2) #ndmin = min dimension
print(a) 

[[1 2 3 4 5]]


### Data types

Data Types | Description
---------- | -------------	
1 bool_ | Boolean (True or False) stored as a byte
2 int_ | Default integer type (same as C long; normally either int64 or int32)
3 intc | Identical to C int (normally int32 or int64)
4 intp | Integer used for indexing (same as C ssize_t; normally either int32 or int64)
5 int8 | Byte (-128 to 127)
6 int16 | Integer (-32768 to 32767)
7 int32 | Integer (-2147483648 to 2147483647)
8 int64 | Integer (-9223372036854775808 to 9223372036854775807)
9 uint8 | Unsigned integer (0 to 255)
10 uint16 | Unsigned integer (0 to 65535)
11 uint32 | Unsigned integer (0 to 4294967295)
12 uint64 | Unsigned integer (0 to 18446744073709551615)
13 float_ | Shorthand for float64
14 float16 | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa
15 float32 | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa
16 float64 | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa
17 complex_ | Shorthand for complex128
18 complex64 | Complex number, represented by two 32-bit floats (real and imaginary components)
19 complex128 | Complex number, represented by two 64-bit floats (real and imaginary components)

In [12]:
a = np.array([1,2,3], dtype=complex)
print(a)
dt = np.dtype(np.float64)
print(np.array([1,2,3], dtype=dt))
dt = np.dtype('>i4') 
# i1=int8, i2=int16, i4=int32, i8=int64
# '>' = big-endian '<' = little endian
print(np.array([1,2,3], dtype=dt))

[ 1.+0.j  2.+0.j  3.+0.j]
[ 1.  2.  3.]
[1 2 3]


### Structured data type

In [14]:
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20, ), (30,)], dtype=dt)
print(a)
print(a['age'])

[(10,) (20,) (30,)]
[10 20 30]


In [21]:
student = np.dtype([('name', '>U21'), ('age', 'i1'), ('marks', 'f4')])
print(student)
s = np.array([('akshay', 21, 90), ('avinash', 21, 100), ('debanjan', 22, 99.9)], dtype=student)
print(s['name'])

[('name', '>U21'), ('age', 'i1'), ('marks', '<f4')]
['akshay' 'avinash' 'debanjan']


### Shape, size and dimension manipulation

In [23]:
a = np.array([[1,2,3], [4,5,6]])
print(a.shape)

(2, 3)


In [25]:
a.shape = (3,2)
# or a.reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
a = np.arange(24)
print(a, a.ndim)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 1


In [32]:
b = a.reshape(2,4,3)
print(b, b.ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]] 3


In [34]:
print(a.itemsize) #returns size of each element in bytes

8


#### Flags:

Attribute  | Description
---------- | ------------------------
1. C_CONTIGUOUS (C)|  The data is in a single, C-style contiguous segment
2. F_CONTIGUOUS (F) | The data is in a single, Fortran-style contiguous segment
3. OWNDATA (O) | The array owns the memory it uses or borrows it from another object
4. WRITEABLE (W) | The data area can be written to. Setting this to False locks the data, making it read-only
5. ALIGNED (A) | The data and all elements are aligned appropriately for the hardware
6. UPDATEIFCOPY (U) | This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array

In [35]:
print(a.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


### ndarray creation without external object
```numpy.empty(shape, dtype = float, order = 'C')```

*Order = 'C' for C-style row-major array, 'F' for FORTRAN style column-major array*

Creates uninitialized array. Contains garbage values.

In [36]:
a = np.empty([3,2], dtype=int) 
print(a) 

[[1 2]
 [3 4]
 [5 6]]


```numpy.zeros(shape, dtype = float, order = 'C')```

Creates array with all elements = 0

```numpy.ones(shape, dtype = None, order = 'C')```

Creates array with all elements = 1


In [38]:
x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]
