# NUMPY BASIC COMMANDS

In [1]:
import numpy as np

### A simple ndarray

In [3]:
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


### Minimum dimension attribute

In [4]:
a = np.array([1,2,3,4,5], ndmin=2) #ndmin = min dimension
print(a) 

[[1 2 3 4 5]]


### Data types

In [12]:
a = np.array([1,2,3], dtype=complex)
print(a)
dt = np.dtype(np.float64)
print(np.array([1,2,3], dtype=dt))
dt = np.dtype('>i4') 
# i1=int8, i2=int16, i4=int32, i8=int64
# '>' = big-endian '<' = little endian
print(np.array([1,2,3], dtype=dt))

[ 1.+0.j  2.+0.j  3.+0.j]
[ 1.  2.  3.]
[1 2 3]
