### Other methods to create ndarray


```numpy.asarray(a, dtype = None, order = None)```

In [4]:
import numpy as np
x=(1,2,3)
a=np.asarray(x, dtype=float)
print(a)

[ 1.  2.  3.]


```numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
numpy.fromiter(iterable, dtype, count = -1)
```

Parameter | Description
--------- | ------------
1 buffer | Any object that exposes buffer interface
2 dtype | Data type of returned ndarray. Defaults to float
3 count | The number of items to read, default -1 means all data
4 offset | The starting position to read from. Default is 0

In [11]:
list = range(5) 
it = iter(list)  
x = np.fromiter(it, dtype = float) 
print(x)

[ 0.  1.  2.  3.  4.]


```numpy.arange(start, stop, step, dtype)```

Parameter | Description
--------- | ------------
1 start | The start of an interval. If omitted, defaults to 0
2 stop | The end of an interval (not including this number)
3 step | Spacing between values, default is 1
4 dtype | Data type of resulting ndarray. If not given, data type of input is used

In [13]:
x = np.arange(5, dtype = float)
print(x)
x = np.arange(10,20,2) 
print(x)

[ 0.  1.  2.  3.  4.]
[10 12 14 16 18]


```numpy.linspace(start, stop, num, endpoint, retstep, dtype)```

Parameter | Description
--------- | ------------
1 num | The number of evenly spaced samples to be generated. Default is 50 
2 endpoint | True by default, hence the stop value is included in the sequence. If false, it is not included
3 retstep | If true, returns samples and step between the consecutive numbers


In [14]:
x = np.linspace(10,20,5) 
print(x)

[ 10.   12.5  15.   17.5  20. ]


In [15]:
x = np.linspace(10,20, 5, endpoint = False) 
print(x)

[ 10.  12.  14.  16.  18.]


In [16]:
x = np.linspace(1,2,5, retstep = True) 
print(x)

(array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ]), 0.25)


``` numpy.logspace(start, stop, num, endpoint, base, dtype)```

base : Base of log space, default is 10

In [17]:
a = np.logspace(1.0, 2.0, num = 10) 
print(a)

[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]


In [18]:
a = np.logspace(1,10,num = 10, base = 2) 
print(a)

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]
